#!/bin/env bash

: ${useclust:=0}
: ${numworkers:=1}

while getopts ":cj:" option
do
 case "${option}"
 in
 c) useclust=1;;
 j) numworkers=${OPTARG}
 esac
done
shift $((OPTIND-1))

set -e

jname="$(basename $(pwd))"

if [ $useclust -eq 1 ]; then
  snakemake -j $numworkers -u cluster.yaml \
  --cluster-sync "bsub -K -J $jname:{rule}:{wildcards} \
  -P {cluster.project} -q {cluster.queue} -m {cluster.partition} \
  -n {cluster.cores} -R \"span[hosts=1] select[mem>{cluster.mem}] \
  rusage[mem={cluster.mem}]\" -W {cluster.time} -L /bin/bash \
  -oo .snakejob/{rule}:{wildcards}.stdout \
  -eo .snakejob/{rule}:{wildcards}.stderr < "
else
  snakemake -j $numworkers
fi
